name: hoc-cung-minh

services:
  - type: web
    name: my-app-service
    env: docker
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: "./entrypoint.sh"
    plan: free
    ports:
      - 8000
